### ISSUE TITLE
Intellij idea stuck

### ISSUE THREAD

**Issue by yueliangwen** [manifold-systems/manifold-simple-gradle-project#1]
Follow the operations:
1、Clone the project and init it.
2、Open the Main.java file.
3、Close the project.

The Intellij idea stuck during "preparing workspace..." when reopening the project.

IntelliJ Idea 2020.2.4
Intellij Manifold Plugin : 2020.1.37

**Comment by rsmckinney** [comment]
@yueliangwen Is there a specific project to clone here?

**Comment by yueliangwen** [comment]
@rsmckinney No，it's just a demo that you can access for describing the problem. The Intellij Idea will work fine when disabling the manifold-plugin or closing the Main.java file.

**Comment by rsmckinney** [comment]
@yueliangwen I can't reproduce this, however I'm testing with latest Manifold Plugin 2020.1.40, please try with that release. Thanks.

**Comment by yueliangwen** [comment]
@rsmckinney It's cannot work with the latest Manifold Plugin 2020.1.40. The problem is not always appearing during the opening idea from the console. The dump file may be useful for you.

[dump.txt](https://github.com/manifold-systems/manifold-simple-gradle-project/files/5634012/dump.txt)

**Comment by rsmckinney** [comment]
Still can't reproduce.  Are you using Windows, Mac, Linux?

**Comment by yueliangwen** [comment]
@rsmckinney Mac.

**Comment by yueliangwen** [comment]
@rsmckinney I reinstall all the plugins that I had installed, it works well.

**Comment by rsmckinney** [comment]
Good the hear, Enjoy!
